services:
    postgres:
        image: postgres:latest
        container_name: postgres
        volumes:
            - /usr/local/var/postgres:/data/db
        environment:
            POSTGRES_USER: "${dbUser}"
            POSTGRES_DB: "${dbDatabaseName}"
            POSTGRES_PASSWORD: "${dbPassword}"
            POSTGRES_INITDB_ARGS : "--encoding=UTF-8"

        restart: "unless-stopped"
  
    proxy:
        image: nginx:latest
        container_name: proxy
        volumes:
            - ./proxy/nginx.conf:/etc/nginx/nginx.conf
        restart: "unless-stopped"
  
    api:
        container_name: api
        build:
            context: ./
            dockerfile: ./Dockerfile
        depends_on:
            - postgres
            - proxy
        restart: "unless-stopped"